export const skills = [
    {
        id: "html5",
        name:"HTML5",
        image: "Aqui ira la imagen que se descargue para esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "css3",
        name: "CSS3",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "javascript",
        name: "JavaScript",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "react",
        name: "React",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "git",
        name: "Git",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "github",
        name: "GitHub",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "vite",
        name: "Vite",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "figma",
        name: "Figma",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "vercel",
        name: "Vercel",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "nodejs",
        name: "Node.js",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "expressjs",
        name: "Express.js",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "mongodb",
        name: "MongoDB",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "mongoose",
        name: "Mongoose",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Technologies",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "problemsolving",
        name: "Problem Solving",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "componentbasearch",
        name: "Component-Based Architecture",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "responsivedesign",
        name: "Responsive Design",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "softwaredesign",
        name: "Software Design",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "accessibility",
        name: "Accessibility",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "documentation",
        name: "Documentation",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
    {
        id: "debugandts",
        name: "Debugging & Troubleshooting",
        image: "Aqui ira la imagen que se descargue oara esta skill",
        category: "Engineering Principles",
        description: "Aqui ira la descripcion de como trabajo con esto",
    },
];
